"""
Audit logging, persistence, and compliance report generation.
Supports: JSON persistence, PDF/CSV export, file integrity hashing.
Aligned with NDPA 2023 / NDPR compliance requirements.
"""

import csv
import hashlib
import io
import json
import os
from datetime import datetime
from pathlib import Path
from typing import List, Dict, Any

try:
    from fpdf import FPDF
    FPDF_AVAILABLE = True
except ImportError:
    FPDF_AVAILABLE = False

# ── Colour constants (for PDF) ────────────────────────────────────────────────
BLUE       = (15, 32, 68)          # #0f2044
GOLD       = (240, 165, 0)         # #f0a500
LIGHT_GRAY = (240, 244, 255)

AUDIT_LOG_PATH = Path("audit_logs.json")

NDPR_STATEMENT = (
    "This report is generated by the NDPR Data Redaction Tool. "
    "All data processing is performed locally — no data is transmitted to external services. "
    "This tool supports data minimisation and pseudonymisation principles under the "
    "Nigeria Data Protection Act (NDPA) 2023 and the Nigeria Data Protection Regulation (NDPR). "
    "Hash-based redactions are irreversible. Retain this report as part of your organisation's "
    "data protection documentation and privacy impact assessments."
)

METHOD_DESCRIPTIONS = {
    "hash":         "SHA-256 (irreversible, deterministic)",
    "pseudonymize": "Pseudonymisation — synthetic realistic replacement",
    "mask":         "Partial masking (e.g. 0803****1234)",
    "remove":       "Column removed entirely",
    "regex":        "Custom regex replacement",
}


# ── File integrity ─────────────────────────────────────────────────────────────
def hash_file(file_bytes: bytes) -> str:
    """Return SHA-256 hex digest of raw file bytes for integrity verification."""
    return hashlib.sha256(file_bytes).hexdigest()


# ── Persistence ────────────────────────────────────────────────────────────────
def load_persisted_logs() -> List[dict]:
    """Load audit entries from audit_logs.json. Returns [] if file missing/corrupt."""
    if not AUDIT_LOG_PATH.exists():
        return []
    try:
        with open(AUDIT_LOG_PATH, "r", encoding="utf-8") as f:
            data = json.load(f)
        return data if isinstance(data, list) else []
    except (json.JSONDecodeError, OSError):
        return []


def persist_log_entry(entry: dict) -> None:
    """Append one entry to audit_logs.json (thread-safe: load → append → save)."""
    logs = load_persisted_logs()
    logs.append(entry)
    try:
        with open(AUDIT_LOG_PATH, "w", encoding="utf-8") as f:
            json.dump(logs, f, ensure_ascii=False, indent=2)
    except OSError:
        pass  # Non-fatal — session state still holds the entry


# ── Main logger class ──────────────────────────────────────────────────────────
class AuditLogger:
    """Creates audit entries and exports them as CSV or PDF."""

    def create_entry(
        self,
        session_id: str,
        original_filename: str,
        file_format: str,
        row_count: int,
        column_count: int,
        redacted_columns: Dict[str, dict],
        stats: Dict[str, dict],
        file_hash: str = "",
        user_note: str = "",
    ) -> dict:
        """Build a structured audit log entry."""
        total_redacted = sum(s.get("count", 0) for s in stats.values())

        summary_parts = []
        for col, s in stats.items():
            method = METHOD_DESCRIPTIONS.get(s.get("method", ""), s.get("method", ""))
            cnt = s.get("count", 0)
            ft = s.get("field_type", "")
            summary_parts.append(f"{col} ({ft}) → {method}: {cnt} values")

        entry = {
            "audit_id":              f"AUD-{session_id}-{datetime.now().strftime('%H%M%S')}",
            "timestamp":             datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
            "session_id":            session_id,
            "original_filename":     original_filename,
            "file_format":           file_format.upper(),
            "rows_processed":        row_count,
            "columns_total":         column_count,
            "columns_redacted":      len(stats),
            "values_redacted_total": total_redacted,
            "file_sha256":           file_hash,
            "redaction_summary":     " | ".join(summary_parts),
            "user_note":             user_note or "",
            "ndpr_compliance":       "NDPA 2023 — Data Minimisation & Pseudonymisation",
        }

        persist_log_entry(entry)
        return entry

    def to_csv_bytes(self, entries: List[dict]) -> bytes:
        """Serialise audit entries to UTF-8 CSV bytes."""
        if not entries:
            return b""
        buf = io.StringIO()
        writer = csv.DictWriter(buf, fieldnames=list(entries[0].keys()))
        writer.writeheader()
        writer.writerows(entries)
        return buf.getvalue().encode("utf-8")

    def to_pdf_bytes(self, entries: List[dict], session_id: str) -> bytes:
        """Generate a professional PDF compliance report."""
        if not FPDF_AVAILABLE:
            raise RuntimeError("fpdf2 not installed — use CSV export.")

        pdf = _ReportPDF(session_id=session_id)
        pdf.set_auto_page_break(auto=True, margin=20)
        pdf.add_page()

        # ── Cover header ──
        pdf.set_fill_color(*BLUE)
        pdf.rect(0, 0, 210, 40, style="F")
        pdf.set_font("Helvetica", "B", 20)
        pdf.set_text_color(255, 255, 255)
        pdf.set_y(12)
        pdf.cell(0, 10, "NDPR Compliance Audit Report", align="C", new_x="LMARGIN", new_y="NEXT")
        pdf.set_font("Helvetica", "", 10)
        pdf.set_text_color(*GOLD)
        pdf.cell(0, 7,
            f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}   |   Session: {session_id}",
            align="C", new_x="LMARGIN", new_y="NEXT")
        pdf.ln(12)

        for idx, entry in enumerate(entries, 1):
            # Entry header bar
            pdf.set_fill_color(*GOLD)
            pdf.set_text_color(*BLUE)
            pdf.set_font("Helvetica", "B", 10)
            pdf.cell(0, 8,
                f"  #{idx}  {entry['audit_id']}  —  {entry['timestamp']}",
                fill=True, new_x="LMARGIN", new_y="NEXT")
            pdf.ln(2)

            pdf.set_text_color(20, 20, 20)
            fields = [
                ("File",              entry["original_filename"]),
                ("Format",            entry["file_format"]),
                ("Rows Processed",    f"{entry['rows_processed']:,}"),
                ("Columns Redacted",  f"{entry['columns_redacted']} of {entry['columns_total']}"),
                ("Values Redacted",   f"{entry['values_redacted_total']:,}"),
                ("SHA-256 (file)",    entry.get("file_sha256", "—")[:48] + "…" if entry.get("file_sha256") else "—"),
                ("Session ID",        entry["session_id"]),
            ]
            for label, value in fields:
                pdf.set_font("Helvetica", "B", 9)
                pdf.cell(50, 6, f"  {label}:", new_x="RIGHT", new_y="NONE")
                pdf.set_font("Helvetica", "", 9)
                pdf.cell(0, 6, value, new_x="LMARGIN", new_y="NEXT")

            # Summary block
            pdf.ln(2)
            pdf.set_font("Helvetica", "B", 9)
            pdf.cell(0, 6, "  Redaction details:", new_x="LMARGIN", new_y="NEXT")
            pdf.set_font("Helvetica", "", 8)
            for part in entry["redaction_summary"].split(" | "):
                pdf.cell(12, 5, "", new_x="RIGHT", new_y="NONE")
                pdf.cell(0, 5, f"• {part}", new_x="LMARGIN", new_y="NEXT")

            if entry.get("user_note"):
                pdf.ln(1)
                pdf.set_font("Helvetica", "I", 8)
                pdf.set_text_color(100, 100, 100)
                pdf.multi_cell(0, 5, f"  Note: {entry['user_note']}", new_x="LMARGIN", new_y="NEXT")
                pdf.set_text_color(20, 20, 20)

            pdf.ln(5)
            pdf.set_draw_color(200, 200, 200)
            pdf.set_line_width(0.2)
            pdf.line(15, pdf.get_y(), 195, pdf.get_y())
            pdf.ln(4)

        # ── Compliance statement page ──
        pdf.add_page()
        pdf.set_font("Helvetica", "B", 13)
        pdf.set_text_color(*BLUE)
        pdf.cell(0, 10, "NDPR / NDPA 2023 Compliance Statement", new_x="LMARGIN", new_y="NEXT")
        pdf.ln(3)
        pdf.set_fill_color(*LIGHT_GRAY)
        pdf.set_font("Helvetica", "", 10)
        pdf.set_text_color(30, 30, 30)
        y0 = pdf.get_y()
        pdf.rect(14, y0 - 1, 182, 40, style="F")
        pdf.set_x(17)
        pdf.multi_cell(176, 6, NDPR_STATEMENT, new_x="LMARGIN", new_y="NEXT")
        pdf.ln(8)
        pdf.set_font("Helvetica", "I", 8)
        pdf.set_text_color(130, 130, 130)
        pdf.multi_cell(0, 5,
            "Disclaimer: This tool is intended for data minimisation and safe test-data "
            "generation. For production deployments handling highly sensitive personal data, "
            "deploy privately on an access-controlled server and obtain appropriate legal advice.",
        )
        return bytes(pdf.output())


class _ReportPDF(FPDF):
    def __init__(self, session_id: str, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.session_id = session_id

    def header(self):
        if self.page_no() == 1:
            return
        self.set_font("Helvetica", "I", 7)
        self.set_text_color(150, 150, 150)
        self.cell(0, 5, "NDPR Data Redaction Tool — Confidential", align="L",
                  new_x="RIGHT", new_y="NONE")
        self.cell(0, 5, f"Page {self.page_no()}", align="R",
                  new_x="LMARGIN", new_y="NEXT")
        self.ln(3)

    def footer(self):
        self.set_y(-10)
        self.set_font("Helvetica", "I", 7)
        self.set_text_color(150, 150, 150)
        self.cell(0, 5,
            "Generated by NDPR Data Redaction Tool | Supports NDPA 2023 Compliance",
            align="C")
